### ISSUE TITLE
Problem with right-side mikepenz/MaterialDrawer

### ISSUE THREAD

**Issue by arghaffari** [arimorty/floatingsearchview#166]
Hi, thanks for the great project.
When I set a right side drawer I will get the following error:

Process: com.arosis.pos.aropay, PID: 31350
                                                                       java.lang.IllegalArgumentException: No drawer view found with gravity LEFT
                                                                           at android.support.v4.widget.DrawerLayout.openDrawer(DrawerLayout.java:1651)
                                                                           at android.support.v4.widget.DrawerLayout.openDrawer(DrawerLayout.java:1637)
                                                                           at com.arlib.floatingsearchview.FloatingSearchView$NavDrawerLeftMenuClickListener.onMenuOpened(FloatingSearchView.java:1959)
                                                                           at com.arlib.floatingsearchview.FloatingSearchView.openMenu(FloatingSearchView.java:936)
                                                                           at com.arlib.floatingsearchview.FloatingSearchView.setMenuIconProgress(FloatingSearchView.java:924)
                                                                           at com.arlib.floatingsearchview.FloatingSearchView$DrawerListener.onDrawerSlide(FloatingSearchView.java:1930)
                                                                           at android.support.v4.widget.DrawerLayout.dispatchOnDrawerSlide(DrawerLayout.java:911)
                                                                           at android.support.v4.widget.DrawerLayout.setDrawerViewOffset(DrawerLayout.java:923)
                                                                           at android.support.v4.widget.DrawerLayout$ViewDragCallback.onViewPositionChanged(DrawerLayout.java:2100)
                                                                           at android.support.v4.widget.ViewDragHelper.continueSettling(ViewDragHelper.java:740)
                                                                           at android.support.v4.widget.DrawerLayout.computeScroll(DrawerLayout.java:1280)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:14228)
                                                                           at android.view.View.getDisplayList(View.java:14278)
                                                                           at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3517)
                                                                           at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3496)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:14198)
                                                                           at android.view.View.getDisplayList(View.java:14278)
                                                                           at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3517)
                                                                           at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3496)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:14198)
                                                                           at android.view.View.getDisplayList(View.java:14278)
                                                                           at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3517)
                                                                           at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3496)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:14198)
                                                                           at android.view.View.getDisplayList(View.java:14278)
                                                                           at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3517)
                                                                           at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3496)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:14198)
                                                                           at android.view.View.getDisplayList(View.java:14278)
                                                                           at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3517)
                                                                           at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3496)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:14198)
                                                                           at android.view.View.getDisplayList(View.java:14278)
                                                                           at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:272)
                                                                           at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:278)
                                                                           at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:317)
                                                                           at android.view.ViewRootImpl.draw(ViewRootImpl.java:2869)
                                                                           at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2706)
                                                                           at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2321)
                                                                           at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1259)
                                                                           at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6455)
                                                                           at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
                                                                           at android.view.Choreographer.doCallbacks(Choreographer.java:603)
                                                                           at android.view.Choreographer.doFrame(Choreographer.java:572)
                                                                           at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
                                                                           at android.os.Handler.handleCallback(Handler.java:815)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                           at android.os.Looper.loop(Looper.java:194)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5534)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

**Comment by arimorty** [comment]
Hi @softiran 

This looks like an issue in the client code. You can provide more info if you want, but I do think the issue is on your side.

Regards,
Ari
