### ISSUE TITLE
SearchSuggestionAdapter - Missing IDs

### ISSUE THREAD

**Issue by DPalagi** [arimorty/floatingsearchview#172]
Hi! 

1) Your library is awesome, and I'm sure it'll save me a lot of time if I need it in the future ;)

2) Unfortunately, I'm having troubles with it : when a call swapSuggestions, to have suggestions, it crashes and tell me :

`java.lang.NoSuchFieldError: No field body of type I in class Lcom/arlib/floatingsearchview/R$id; or its superclasses (declaration of 'com.arlib.floatingsearchview.R$id' appears in /data/data/fr.kinaxia.cityscan/files/instant-run/dex/slice-slice_0-classes.dex)
                                                                         at com.arlib.floatingsearchview.suggestions.SearchSuggestionsAdapter$SearchSuggestionViewHolder.<init>(SearchSuggestionsAdapter.java:87)
                                                                         at com.arlib.floatingsearchview.suggestions.SearchSuggestionsAdapter.onCreateViewHolder(SearchSuggestionsAdapter.java:143)
                                                                         at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6290)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5478)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5363)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5359)
                                                                         at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2141)
                                                                         at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1525)
                                                                         at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1488)
                                                                         at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:560)
                                                                         at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3506)
                                                                         at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3254)
                                                                         at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3767)
                                                                         at android.view.View.layout(View.java:17641)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                         at android.view.View.layout(View.java:17641)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                         at android.view.View.layout(View.java:17641)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                         at android.view.View.layout(View.java:17641)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                         at com.arlib.floatingsearchview.FloatingSearchView.onLayout(FloatingSearchView.java:383)
                                                                         at android.view.View.layout(View.java:17641)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                         at android.view.View.layout(View.java:17641)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1167)
                                                                         at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:852)
                                                                         at android.support.design.widget.ViewOffsetBehavior.layoutChild(ViewOffsetBehavior.java:63)
                                                                         at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:135)
                                                                         at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                         at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1375)
                                                                         at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:870)
                                                                         at android.view.View.layout(View.java:17641)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
                                                                         at android.view.View.layout(View.java:17641)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)`

==> it's missing R.id.body and R.id.left_icon in the SearchSuggestionAdapter. But when I look in source code on Github, I can see them in the layout file...

If you have a workaround, or if I'm missing something, just let me know ;)

Thank you in advance,

Regards

**Comment by DPalagi** [comment]
I finally found a solution : I had a file named "search_suggestion_item.xml", just like in your library... So there was a conflict between the 2 and the R.java file was not created correctly ==> missing IDs.

Thanks again for your work ;)

**Comment by arimorty** [comment]
You are very welcome!
Ari
