### ISSUE TITLE
issue in Layout XML

### ISSUE THREAD

**Issue by usmaniqbal998** [arimorty/floatingsearchview#217]
i am getting following exceptions when i try to add floating search view in my fragment XML

android.content.res.Resources$NotFoundException: Could not resolve resource value: 0x7FFF024D.
	at android.content.res.Resources_Delegate.throwException(Resources_Delegate.java:932)
	at android.content.res.Resources_Delegate.throwException(Resources_Delegate.java:919)
	at android.content.res.Resources_Delegate.getDrawable(Resources_Delegate.java:165)
	at android.content.res.Resources.getDrawable(Resources.java:763)
	at android.support.v4.content.res.ResourcesCompatApi21.getDrawable(ResourcesCompatApi21.java:27)
	at android.support.v4.content.res.ResourcesCompat.getDrawable(ResourcesCompat.java:60)
	at com.arlib.floatingsearchview.util.Util.getWrappedDrawable(Util.java:118)
	at com.arlib.floatingsearchview.FloatingSearchView.initDrawables(FloatingSearchView.java:376)
	at com.arlib.floatingsearchview.FloatingSearchView.init(FloatingSearchView.java:350)
	at com.arlib.floatingsearchview.FloatingSearchView.<init>(FloatingSearchView.java:333)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:465)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:172)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:105)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:186)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:334)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:345)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:245)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:324)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:429)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:389)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:548)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:533)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:966)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:533)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$70(RenderTask.java:659)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by arimorty** [comment]
There is no way for us to help without info on the device dimensions of the device it was run on since it looks like that device didn't pick up any of the drawable folders.
