### ISSUE TITLE
No static field divider of type I in class Lcom/arlib/floatingsearchview/R$color

### ISSUE THREAD

**Issue by msroid** [arimorty/floatingsearchview#287]
hi,
i am using this awesome library and everything was ok. but now it doesn't work.
this is my logcat error message:

`FATAL EXCEPTION: main
                                                   Process: ir.msroid.testfloatingsearch, PID: 31991
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{ir.msroid.testfloatingsearch/ir.msroid.testfloatingsearch.MainActivity}: android.view.InflateException: Binary XML file line #9: Error inflating class com.arlib.floatingsearchview.FloatingSearchView
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                    Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class com.arlib.floatingsearchview.FloatingSearchView
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:633)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                       at ir.msroid.testfloatingsearch.MainActivity.onCreate(MainActivity.java:11)
                                                       at android.app.Activity.performCreate(Activity.java:5990)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:135) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                       at java.lang.reflect.Constructor.newInstance(Native Method)
                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:607)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                       at ir.msroid.testfloatingsearch.MainActivity.onCreate(MainActivity.java:11) 
                                                       at android.app.Activity.performCreate(Activity.java:5990) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:135) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
                                                    Caused by: java.lang.NoSuchFieldError: No static field divider of type I in class Lcom/arlib/floatingsearchview/R$color; or its superclasses (declaration of 'com.arlib.floatingsearchview.R$color' appears in /data/app/ir.msroid.testfloatingsearch-2/base.apk)
                                                       at com.arlib.floatingsearchview.FloatingSearchView.applyXmlAttributes(FloatingSearchView.java:532)
                                                       at com.arlib.floatingsearchview.FloatingSearchView.setupViews(FloatingSearchView.java:445)
                                                       at com.arlib.floatingsearchview.FloatingSearchView.init(FloatingSearchView.java:387)
                                                       at com.arlib.floatingsearchview.FloatingSearchView.<init>(FloatingSearchView.java:360)
                                                       at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                       at ir.msroid.testfloatingsearch.MainActivity.onCreate(MainActivity.java:11) 
                                                       at android.app.Activity.performCreate(Activity.java:5990) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:135) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
`

please help me.

**Comment by darylsze** [comment]
reply in 2018..

add a color name 'divider' on your color.xml solves the problem
dont ask me why i hv no idea at all.
