### ISSUE TITLE
Floating Search View causes RuntimeException when inflating NavigationView in the same activity

### ISSUE THREAD

**Issue by walee-balogun** [arimorty/floatingsearchview#3]
I get this error when combining the new material design support library for navigation drawer (Navigation View) with the floating Search View.

Here's my stack trace:

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.robocoders.sampleapp/com.robocoders.sampleapp.ui.activity.MainActivity}: android.view.InflateException: Binary XML file line #242: Error inflating class android.support.design.widget.NavigationView
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2521)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2601)
       at android.app.ActivityThread.access$800(ActivityThread.java:178)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5637)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
Caused by android.view.InflateException: Binary XML file line #242: Error inflating class android.support.design.widget.NavigationView
       at android.view.LayoutInflater.createView(LayoutInflater.java:633)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256)
       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
       at com.robocoders.sampleapp.ui.activity.MainActivity.onCreate(MainActivity.java:101)
       at android.app.Activity.performCreate(Activity.java:6092)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2468)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2601)
       at android.app.ActivityThread.access$800(ActivityThread.java:178)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5637)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
       at android.view.LayoutInflater.createView(LayoutInflater.java:607)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256)
       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
       at com.robocoders.sampleapp.ui.activity.MainActivity.onCreate(MainActivity.java:101)
       at android.app.Activity.performCreate(Activity.java:6092)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2468)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2601)
       at android.app.ActivityThread.access$800(ActivityThread.java:178)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5637)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
Caused by java.lang.NoClassDefFoundError: android.support.design.internal.NavigationMenuPresenter
       at android.support.design.widget.NavigationView.<init>(NavigationView.java:80)
       at android.support.design.widget.NavigationView.<init>(NavigationView.java:92)
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
       at android.view.LayoutInflater.createView(LayoutInflater.java:607)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256)
       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
       at com.iconway.padi.ui.activity.MainActivity.onCreate(MainActivity.java:101)
       at android.app.Activity.performCreate(Activity.java:6092)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2468)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2601)
       at android.app.ActivityThread.access$800(ActivityThread.java:178)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5637)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

**Comment by arimorty** [comment]
I cannot see from your logs that FloatingSearchView is the issue. Try to see if something else is causing the problem.
