### ISSUE TITLE
java.lang.NoClassDefFoundError 

### ISSUE THREAD

**Issue by ernestkamara** [arimorty/floatingsearchview#45]
Missing proguard-rules?

`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bartoszlipinski/viewpropertyobjectanimator/ViewPropertyObjectAnimator;
        at com.arlib.floatingsearchview.FloatingSearchView.transitionInLeftSection(FloatingSearchView.java:1406)
        at com.arlib.floatingsearchview.FloatingSearchView.setSearchFocusedInternal(FloatingSearchView.java:1319)
        at com.arlib.floatingsearchview.FloatingSearchView.access$1500(FloatingSearchView.java:87)
        at com.arlib.floatingsearchview.FloatingSearchView$7.onFocusChange(FloatingSearchView.java:609)
        at android.view.View.onFocusChanged(View.java:5723)
        at android.widget.TextView.onFocusChanged(TextView.java:8224)
        at android.view.View.handleFocusGainInternal(View.java:5478)
        at android.view.View.requestFocusNoSearch(View.java:8476)
        at android.view.View.requestFocus(View.java:8455)
        at android.view.View.requestFocus(View.java:8422)
        at android.view.View.requestFocus(View.java:8401)
        at android.view.View.onTouchEvent(View.java:10305)
        at android.widget.TextView.onTouchEvent(TextView.java:8300)
        at android.view.View.dispatchTouchEvent(View.java:9300)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
        at android.app.Activity.dispatchTouchEvent(Activity.java:2771)
        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
        at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
        at android.view.View.dispatchPointerEvent(View.java:9520)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4238)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4104)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3703)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3669)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3795)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3677)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3852)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3703)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3669)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3677)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5932)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5906)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5867)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6035)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:323)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5422)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.bartoszlipinski.viewpropertyobjectanimator.ViewProp
                            ertyObjectAnimator" on path: DexPathList[[zip file "/data/app/net.zedge.snakk-2/base.apk"],nativeLibraryDirectories=[/d
                            ata/app/net.zedge.snakk-2/lib/arm64, /vendor/lib64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        ... 71 more
        Suppressed: java.lang.ClassNotFoundException: com.bartoszlipinski.viewpropertyobjectanimator.ViewPropertyObjectAnim
                            ator
            at java.lang.Class.classForName(Native Method)
            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
            ... 72 more
        Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
            FlurryAgent  W  Error logged: uncaught
    Flurry session ended`

**Comment by arimorty** [comment]
Hello, @ernestkamara. I appreciate your contributions to this library. 

I am getting ready for releasing version 2.2.0, and I would appreciate if you can suggest improvements and/or add a PR for the changes you have made on your fork.

Also, I will be merging https://github.com/arimorty/floatingsearchview/tree/improvements into develop soon, and it would help if you can test that branch before the merge.

Thank you,

**Comment by ernestkamara** [comment]
You are welcome @arimorty. I will check it out later after office hours. Btw, have you converted the library from Maven to Gradle? It would be nice to have it working with Gradle, since it makes building and test the library faster and easier.

**Comment by arimorty** [comment]
I might be missing something, but the library is, in fact, using Gradle. I only use Maven for publishing the library and make it available to be used in build.gradle dependencies. 

That being said, only the current/previous versions in master branch are published, the ones in development are not.

**Comment by ernestkamara** [comment]
You were right @arimorty, the library is using Gradle, but uses Maven for publishing. I had to change my [fork](https://github.com/ernestkamara/floatingsearchview/blob/proguard-config/library/build.gradle) to publish using Chris Banes' [gradle-mvn-push script](https://raw.githubusercontent.com/chrisbanes/gradle-mvn-push/master/gradle-mvn-push.gradle), since i can easily export the generated aar file. 

I also set minifyEnabled to true in my release buildType, since i want to turn on code shrinking. Doing that without any proguard-rules would trigger the following crash above. I was wondering why minifyEnabled is set to false in the [library](https://github.com/arimorty/floatingsearchview/blob/master/library/build.gradle)?

**Comment by arimorty** [comment]
No reason, just missed it.

**Comment by ernestkamara** [comment]
Any plans fixing this in the upcoming release? Not sure if your need a PR from me on this, if you are already working on adding some proguard-rules.

**Comment by arimorty** [comment]
I can just look at your branch and see, I do have to look into it more
thoroughly before I know if I'll integrate it next release.
