### ISSUE TITLE
java.lang.RuntimeException: Parcel android.os.Parcel@3b13f01: Unmarshalling unknown type code 7471204 at offset 944

### ISSUE THREAD

**Issue by SilverFoxA** [arimorty/floatingsearchview#53]
I'm getting the following error adding the library, can anyone please help me with this? I have not yet implemented any code other than the XML

`java.lang.RuntimeException: Unable to start activity ComponentInfo{package.V1.BaseClasses.MainActivity}: java.lang.RuntimeException: Parcel android.os.Parcel@3b13f01: Unmarshalling unknown type code 7471204 at offset 944
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
                                                                    at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                                 Caused by: java.lang.RuntimeException: Parcel android.os.Parcel@3b13f01: Unmarshalling unknown type code 7471204 at offset 944
                                                                    at android.os.Parcel.readValue(Parcel.java:2340)
                                                                    at android.os.Parcel.readSparseArrayInternal(Parcel.java:2675)
                                                                    at android.os.Parcel.readSparseArray(Parcel.java:1967)
                                                                    at android.os.Parcel.readValue(Parcel.java:2321)
                                                                    at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
                                                                    at android.os.BaseBundle.unparcel(BaseBundle.java:221)
                                                                    at android.os.Bundle.getSparseParcelableArray(Bundle.java:856)
                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:997)
                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
                                                                    at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:2041)
                                                                    at android.support.v4.app.FragmentController.dispatchCreate(FragmentController.java:163)
                                                                    at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:331)
                                                                    at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:85)
                                                                    at package.V1.BaseClasses.MainActivity.onCreate(MainActivity.java:58)
                                                                    at android.app.Activity.performCreate(Activity.java:6245)
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                                                    at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:148) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) `

**Comment by ernestkamara** [comment]
See #32 for a quick fix. I would be sending a PR to fix this in the next release.
