### ISSUE TITLE
NullPointerException with MenuView.filter

### ISSUE THREAD

**Issue by ernestkamara** [arimorty/floatingsearchview#72]
Don't know if this has been fixed in 2.0.1, but seems to be happening on Samsung Note 2 (gt_n7105t) running Android 4.3 and 4.4.2. Our app is still in beta and hasn't been updated to  2.0.1 yet.

```
Caused by java.lang.NullPointerException
       at com.arlib.floatingsearchview.util.view.MenuView.filter(MenuView.java:526)
       at com.arlib.floatingsearchview.util.view.MenuView.hideIfRoomItems(MenuView.java:291)
       at com.arlib.floatingsearchview.FloatingSearchView.setSearchFocusedInternal(FloatingSearchView.java:1336)
       at com.arlib.floatingsearchview.FloatingSearchView.access$1500(FloatingSearchView.java:87)
       at com.arlib.floatingsearchview.FloatingSearchView$7.onFocusChange(FloatingSearchView.java:609)
       at android.view.View.onFocusChanged(View.java:5055)
       at android.widget.TextView.onFocusChanged(TextView.java:9169)
       at android.widget.EditText.onFocusChanged(EditText.java:182)
       at android.view.View.handleFocusGainInternal(View.java:4835)
       at android.view.View.requestFocusNoSearch(View.java:7251)
       at android.view.View.requestFocus(View.java:7230)
       at android.view.View.requestFocus(View.java:7197)
       at android.view.View.requestFocus(View.java:7176)
       at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:1960)
       at android.app.Dialog.onRestoreInstanceState(Dialog.java:431)
       at android.support.v4.app.DialogFragment.onActivityCreated(DialogFragment.java:396)
       at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1983)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1092)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2046)
       at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:174)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:598)
       at net.zedge.snakk.activity.ControllerActivity.onStart(ControllerActivity.java:300)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1177)
       at android.app.Activity.performStart(Activity.java:5461)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2386)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
       at android.app.ActivityThread.access$900(ActivityThread.java:175)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5602)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by arimorty** [comment]
@ernestkamara can you confirm that this is still an issue with version 2.0.1?

**Comment by ernestkamara** [comment]
Hey @arimorty ,
Here is the lastes crash on this issue after upgrading to 2.0.3
Crashing on the following devices:
Samsung SGH-T399
Enspert (RAINBOW)

`Fatal Exception: android.view.InflateException: Binary XML file line #9: Error inflating class com.arlib.floatingsearchview.FloatingSearchView
       at android.view.LayoutInflater.createView(LayoutInflater.java:619)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at net.zedge.snakk.fragment.BaseThumbListFragment.onCreateView(BaseThumbListFragment.java:42)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
       at android.support.v4.app.Fragment.performStart(Fragment.java:1996)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1102)
       at android.support.v4.app.FragmentManagerImpl.performPendingDeferredStart(FragmentManager.java:926)
       at android.support.v4.app.FragmentManagerImpl.startPendingDeferredFragments(FragmentManager.java:1276)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1634)
       at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
       at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1025)
       at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1545)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
       at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:668)
       at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:735)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:720)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:592)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2544)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2195)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1340)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1551)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1237)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5162)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
       at android.view.Choreographer.doCallbacks(Choreographer.java:591)
       at android.view.Choreographer.doFrame(Choreographer.java:561)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
       at android.os.Handler.handleCallback(Handler.java:725)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:5299)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
       at android.view.LayoutInflater.createView(LayoutInflater.java:593)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at net.zedge.snakk.fragment.BaseThumbListFragment.onCreateView(BaseThumbListFragment.java:42)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
       at android.support.v4.app.Fragment.performStart(Fragment.java:1996)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1102)
       at android.support.v4.app.FragmentManagerImpl.performPendingDeferredStart(FragmentManager.java:926)
       at android.support.v4.app.FragmentManagerImpl.startPendingDeferredFragments(FragmentManager.java:1276)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1634)
       at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
       at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1025)
       at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1545)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
       at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:668)
       at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:735)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:720)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:592)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2544)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2195)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1340)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1551)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1237)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5162)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
       at android.view.Choreographer.doCallbacks(Choreographer.java:591)
       at android.view.Choreographer.doFrame(Choreographer.java:561)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
       at android.os.Handler.handleCallback(Handler.java:725)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:5299)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by android.view.InflateException: Binary XML file line #82: Error inflating class com.arlib.floatingsearchview.util.view.MenuView
       at android.view.LayoutInflater.createView(LayoutInflater.java:619)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:846)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:742)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
       at android.view.View.inflate(View.java:17473)
       at com.arlib.floatingsearchview.FloatingSearchView.init(FloatingSearchView.java:341)
       at com.arlib.floatingsearchview.FloatingSearchView.<init>(FloatingSearchView.java:333)
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
       at android.view.LayoutInflater.createView(LayoutInflater.java:593)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at net.zedge.snakk.fragment.BaseThumbListFragment.onCreateView(BaseThumbListFragment.java:42)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
       at android.support.v4.app.Fragment.performStart(Fragment.java:1996)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1102)
       at android.support.v4.app.FragmentManagerImpl.performPendingDeferredStart(FragmentManager.java:926)
       at android.support.v4.app.FragmentManagerImpl.startPendingDeferredFragments(FragmentManager.java:1276)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1634)
       at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
       at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1025)
       at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1545)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
       at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:668)
       at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:735)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:720)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:592)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2544)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2195)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1340)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1551)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1237)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5162)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
       at android.view.Choreographer.doCallbacks(Choreographer.java:591)
       at android.view.Choreographer.doFrame(Choreographer.java:561)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
       at android.os.Handler.handleCallback(Handler.java:725)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:5299)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
       at android.view.LayoutInflater.createView(LayoutInflater.java:593)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:846)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:742)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
       at android.view.View.inflate(View.java:17473)
       at com.arlib.floatingsearchview.FloatingSearchView.init(FloatingSearchView.java:341)
       at com.arlib.floatingsearchview.FloatingSearchView.<init>(FloatingSearchView.java:333)
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
       at android.view.LayoutInflater.createView(LayoutInflater.java:593)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at net.zedge.snakk.fragment.BaseThumbListFragment.onCreateView(BaseThumbListFragment.java:42)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
       at android.support.v4.app.Fragment.performStart(Fragment.java:1996)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1102)
       at android.support.v4.app.FragmentManagerImpl.performPendingDeferredStart(FragmentManager.java:926)
       at android.support.v4.app.FragmentManagerImpl.startPendingDeferredFragments(FragmentManager.java:1276)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1634)
       at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
       at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1025)
       at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1545)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
       at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:668)
       at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:735)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:720)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:592)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2544)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2195)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1340)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1551)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1237)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5162)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
       at android.view.Choreographer.doCallbacks(Choreographer.java:591)
       at android.view.Choreographer.doFrame(Choreographer.java:561)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
       at android.os.Handler.handleCallback(Handler.java:725)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:5299)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.NoClassDefFoundError: android.support.v7.view.menu.MenuBuilder
       at com.arlib.floatingsearchview.util.view.MenuView.init(MenuView.java:100)
       at com.arlib.floatingsearchview.util.view.MenuView.<init>(MenuView.java:96)
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
       at android.view.LayoutInflater.createView(LayoutInflater.java:593)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:846)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:742)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
       at android.view.View.inflate(View.java:17473)
       at com.arlib.floatingsearchview.FloatingSearchView.init(FloatingSearchView.java:341)
       at com.arlib.floatingsearchview.FloatingSearchView.<init>(FloatingSearchView.java:333)
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
       at android.view.LayoutInflater.createView(LayoutInflater.java:593)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at net.zedge.snakk.fragment.BaseThumbListFragment.onCreateView(BaseThumbListFragment.java:42)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
       at android.support.v4.app.Fragment.performStart(Fragment.java:1996)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1102)
       at android.support.v4.app.FragmentManagerImpl.performPendingDeferredStart(FragmentManager.java:926)
       at android.support.v4.app.FragmentManagerImpl.startPendingDeferredFragments(FragmentManager.java:1276)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1634)
       at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
       at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1025)
       at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1545)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
       at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:668)
       at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:735)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:720)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:592)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2544)
       at android.view.View.measure(View.java:16451)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2195)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1340)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1551)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1237)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5162)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
       at android.view.Choreographer.doCallbacks(Choreographer.java:591)
       at android.view.Choreographer.doFrame(Choreographer.java:561)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
       at android.os.Handler.handleCallback(Handler.java:725)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:5299)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
       at dalvik.system.NativeStart.main(NativeStart.java)`
